import { prisma, PrismaSeederBase } from '@ioc:Adonis/Addons/Prisma'
import { Prisma } from '@prisma/client';

const responsabilitiesEntesData : Prisma.ResponsiblesEntesCreateManyInput[] = [
  {
    enteId: 31,
    responsabilityId: 5,
    professionId: 1,
    firstName: 'JEFERSON',
    lastName: 'CAMEJO',
    identity: '16512897',
    gender: 1,
    birthDate: '',
    email: 'camejo1984@gmail.com',
    phone: ''
  },
  {
    enteId: 32,
    responsabilityId: 5,
    professionId: 1,
    firstName: 'VICTOR',
    lastName: 'HUGO',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
    email: 'camejo1984@gmail.com'
  },
  {
    enteId: 33,
    responsabilityId: 5,
    professionId: 1,
    firstName: 'RONNY JOSE',
    lastName: 'YEGUEZ MASS',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
    email: 'ronnyeguez@gmail.com'
  },
  {
    enteId: 34,
    responsabilityId: 5,
    professionId: 1,
    email: 'pedromerentes@gmail.com',
    firstName: 'PEDRO',
    lastName: 'MERENTES',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 35,
    responsabilityId: 5,
    professionId: 1,
    email: 'mfutbarinas@gmail.com',
    firstName: 'ZAIRA',
    lastName: 'VIVAS',
    identity: '',
    phone: '',
    gender: 0,
    birthDate: '',
  },
  {
    enteId: 36,
    responsabilityId: 5,
    professionId: 1,
    email: 'presidencia.fundacitebolivar@gmail.com',
    firstName: 'LUIS',
    lastName: 'CÁRDENAS',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 37,
    responsabilityId: 5,
    professionId: 1,
    email: 'presidentefundacite@gmail.com',
    firstName: 'EFRAÍN',
    lastName: 'MARÍN',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 38,
    responsabilityId: 5,
    professionId: 1,
    email: 'utfundacitecojedes@gmail.com',
    firstName: 'PABLO',
    lastName: 'RODRIGUEZ',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 39,
    responsabilityId: 5,
    professionId: 1,
    email: 'presidenciafundacitedelta@gmail.com',
    firstName: 'JHONNY',
    lastName: 'GOMEZ',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 40,
    responsabilityId: 5,
    professionId: 1,
    email: 'yugre202003@gmail.com',
    firstName: 'JUOGREIDIN',
    lastName: 'CERERO',
    identity: '',
    phone: '',
    gender: 0,
    birthDate: '',
  },
  {
    enteId: 41,
    responsabilityId: 5,
    professionId: 1,
    email: 'jjmadridh@gmail.com',
    firstName: 'JIM JOSE',
    lastName: 'MADRID',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 42,
    responsabilityId: 5,
    professionId: 1,
    email: 'presidenciafundacitelara1@gmail.com',
    firstName: 'ANGÉLICA',
    lastName: 'GONZALEZ',
    identity: '',
    phone: '',
    gender: 0,
    birthDate: '',
  },
  {
    enteId: 43,
    responsabilityId: 5,
    professionId: 1,
    email: 'mmora.fundacite@gmail.com',
    firstName: 'MARIA NATHALY',
    lastName: 'MORA',
    identity: '',
    phone: '',
    gender: 0,
    birthDate: '',
  },
  {
    enteId: 44,
    responsabilityId: 5,
    professionId: 1,
    email: 'hector.constant@gmail.com',
    firstName: 'HECTOR',
    lastName: 'CONSTANT',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 45,
    responsabilityId: 5,
    professionId: 1,
    email: 'ariamandrea26@gmail.com',
    firstName: 'MARIA',
    lastName: 'HERNANDEZ',
    identity: '',
    phone: '',
    gender: 0,
    birthDate: '',
  },
  {
    enteId: 46,
    responsabilityId: 5,
    professionId: 1,
    email: 'presidenciafundacitene@gmail.com',
    firstName: 'VANESSA',
    lastName: 'MALDONADO',
    identity: '',
    phone: '',
    gender: 0,
    birthDate: '',
  },
  {
    enteId: 47,
    responsabilityId: 5,
    professionId: 1,
    email: 'symoncatt@gmail.com',
    firstName: 'SIMÓN',
    lastName: 'BONILLA',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 48,
    responsabilityId: 5,
    professionId: 1,
    email: 'sociologo.dygt@gmail.com',
    firstName: 'ENRIQUE',
    lastName: 'ORTIZ',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 49,
    responsabilityId: 5,
    professionId: 1,
    email: 'oscarjforero83@gmail.com',
    firstName: 'OSCAR',
    lastName: 'FORERO',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 50,
    responsabilityId: 5,
    professionId: 1,
    email: 'jeaneth.montero@gmail.com',
    firstName: 'JEANETH',
    lastName: 'MONTERO',
    identity: '',
    phone: '',
    gender: 0,
    birthDate: '',
  },
  {
    enteId: 51,
    responsabilityId: 5,
    professionId: 1,
    email: 'miguelangel1989.33@gmail.com',
    firstName: 'MIGUEL ANGEL',
    lastName: 'SOLORZANO BELIZARIO',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  },
  {
    enteId: 52,
    responsabilityId: 5,
    professionId: 1,
    email: 'joselarezve@gmail.com',
    firstName: 'JOSE RAFAEL',
    lastName: 'LAREZ RUBIO',
    identity: '',
    phone: '',
    gender: 1,
    birthDate: '',
  }
]

export default class ResponsabilitiesEnteSeeder extends PrismaSeederBase {
  public static developmentOnly = false

  public async run() {
    await prisma.responsiblesEntes.createMany({ data: responsabilitiesEntesData, skipDuplicates: true });
  }
}
